/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kapott_hbci_passport_HBCIPassportDDV */

#ifndef _Included_org_kapott_hbci_passport_HBCIPassportDDV
#define _Included_org_kapott_hbci_passport_HBCIPassportDDV
#ifdef __cplusplus
extern "C" {
#endif
#undef org_kapott_hbci_passport_HBCIPassportDDV_FOR_SAVE
#define org_kapott_hbci_passport_HBCIPassportDDV_FOR_SAVE 1L
#undef org_kapott_hbci_passport_HBCIPassportDDV_FOR_LOAD
#define org_kapott_hbci_passport_HBCIPassportDDV_FOR_LOAD 0L
/* Inaccessible static: CIPHER_SALT */
#undef org_kapott_hbci_passport_HBCIPassportDDV_CIPHER_ITERATIONS
#define org_kapott_hbci_passport_HBCIPassportDDV_CIPHER_ITERATIONS 987L
/*
 * Class:     org_kapott_hbci_passport_HBCIPassportDDV
 * Method:    initCT
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kapott_hbci_passport_HBCIPassportDDV_initCT
  (JNIEnv *, jobject);

/*
 * Class:     org_kapott_hbci_passport_HBCIPassportDDV
 * Method:    ctReadBankData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kapott_hbci_passport_HBCIPassportDDV_ctReadBankData
  (JNIEnv *, jobject);

/*
 * Class:     org_kapott_hbci_passport_HBCIPassportDDV
 * Method:    ctReadKeyData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kapott_hbci_passport_HBCIPassportDDV_ctReadKeyData
  (JNIEnv *, jobject);

/*
 * Class:     org_kapott_hbci_passport_HBCIPassportDDV
 * Method:    ctEnterPIN
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kapott_hbci_passport_HBCIPassportDDV_ctEnterPIN
  (JNIEnv *, jobject);

/*
 * Class:     org_kapott_hbci_passport_HBCIPassportDDV
 * Method:    ctSaveBankData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kapott_hbci_passport_HBCIPassportDDV_ctSaveBankData
  (JNIEnv *, jobject);

/*
 * Class:     org_kapott_hbci_passport_HBCIPassportDDV
 * Method:    ctSaveSigId
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kapott_hbci_passport_HBCIPassportDDV_ctSaveSigId
  (JNIEnv *, jobject);

/*
 * Class:     org_kapott_hbci_passport_HBCIPassportDDV
 * Method:    ctSign
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_kapott_hbci_passport_HBCIPassportDDV_ctSign
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_kapott_hbci_passport_HBCIPassportDDV
 * Method:    ctEncrypt
 * Signature: ()[[B
 */
JNIEXPORT jobjectArray JNICALL Java_org_kapott_hbci_passport_HBCIPassportDDV_ctEncrypt
  (JNIEnv *, jobject);

/*
 * Class:     org_kapott_hbci_passport_HBCIPassportDDV
 * Method:    ctDecrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_kapott_hbci_passport_HBCIPassportDDV_ctDecrypt
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_kapott_hbci_passport_HBCIPassportDDV
 * Method:    closeCT
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kapott_hbci_passport_HBCIPassportDDV_closeCT
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
